  version: '3.7'

  networks:
    backend:
      driver: bridge

  services:

  database:
    working_dir: /app/database/
      image: postgres
      container_name: database
        # restart: unless-stopped
      expose:
        - 5432
      ports:
        - "5432:5432"
      volumes:
        - ./database:/app/database/
#        - ./database/ddl:/docker-entrypoint-initdb.d/     directory would be load and run inside of container on creation.
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=password
      networks:
        - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "2222:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - backend
    depends_on:
      - database